@echo off
setlocal EnableDelayedExpansion
title Start Embranch Daemon (TEST)

REM Generated by Install-Harness.ps1 v2.18.2
REM Project: TEST  (D:\Extracted\260521_GitTest\ProjectA)

set "EMBRANCH_DEFAULT_PORT=9473"
set "EMBRANCH_LOG_DIR=%LOCALAPPDATA%\Embranch\logs"
set "SLOTS_JSON=%LOCALAPPDATA%\Embranch\slots.json"
set "MCP_JSON=D:\Extracted\260521_GitTest\ProjectA\.mcp.json"
set "_exit=0"

REM --- EMBR-350: Detect version from .mcp.json and resolve slot from slots.json ---
set "EMBRANCH_DAEMON_PORT=%EMBRANCH_DEFAULT_PORT%"
set "PINNED_VERSION="
set "SLOT_NUM="
set "SLOT_BIN="

if not exist "%MCP_JSON%" goto skip_version_detect
for /f "tokens=*" %%L in ('powershell -NoProfile -NonInteractive -Command "$mcp = Get-Content $env:MCP_JSON -Raw | ConvertFrom-Json; $url = $mcp.mcpServers.psdd.url; if ($url -match '/embranch/v([^/]+)/') { $Matches[1] }" 2^>nul') do set "PINNED_VERSION=%%L"
:skip_version_detect

if not exist "%SLOTS_JSON%" goto skip_slot_resolve
if not defined PINNED_VERSION goto resolve_default_slot

REM --- Pinned version: find matching slot ---
for /f "tokens=1,2,3" %%A in ('powershell -NoProfile -NonInteractive -Command "$reg = Get-Content $env:SLOTS_JSON -Raw | ConvertFrom-Json; foreach ($p in $reg.slots.PSObject.Properties) { if ($p.Value.version -eq $env:PINNED_VERSION) { Write-Output ($p.Name + ' ' + $p.Value.internal_port + ' ' + $p.Value.binary_path); break } }" 2^>nul') do (
    set "SLOT_NUM=%%A"
    set "EMBRANCH_DAEMON_PORT=%%B"
    set "SLOT_BIN=%%C"
)
goto skip_slot_resolve

:resolve_default_slot
REM --- No pin: use default slot from slots.json ---
for /f "tokens=1,2,3" %%A in ('powershell -NoProfile -NonInteractive -Command "$reg = Get-Content $env:SLOTS_JSON -Raw | ConvertFrom-Json; $dk = [string]$reg.default_slot; if ($reg.slots.PSObject.Properties[$dk]) { $e = $reg.slots.$dk; Write-Output ($dk + ' ' + $e.internal_port + ' ' + $e.binary_path) }" 2^>nul') do (
    set "SLOT_NUM=%%A"
    set "EMBRANCH_DAEMON_PORT=%%B"
    set "SLOT_BIN=%%C"
)

:skip_slot_resolve

REM --- Resolve binary: slot binary_path > default slot > daemon\current ---
set "EMBRANCH_BIN="
if defined SLOT_BIN if exist "%SLOT_BIN%" set "EMBRANCH_BIN=%SLOT_BIN%"

if defined EMBRANCH_BIN goto resolved_bin
if not exist "%SLOTS_JSON%" goto use_current_bin
for /f "tokens=*" %%B in ('powershell -NoProfile -NonInteractive -Command "$reg = Get-Content $env:SLOTS_JSON -Raw | ConvertFrom-Json; $dk = [string]$reg.default_slot; if ($reg.slots.PSObject.Properties[$dk] -and $reg.slots.$dk.binary_path) { $reg.slots.$dk.binary_path }" 2^>nul') do set "EMBRANCH_BIN=%%B"
if defined EMBRANCH_BIN goto resolved_bin
:use_current_bin
set "EMBRANCH_BIN=%LOCALAPPDATA%\Embranch\daemon\current\embranch-daemon.exe"
:resolved_bin

set "HEALTH_URL=http://127.0.0.1:%EMBRANCH_DAEMON_PORT%/health"

echo.
echo Embranch Daemon -- Start
echo   Project: TEST
if defined PINNED_VERSION (
    echo   Pinned:  v%PINNED_VERSION%  ^(slot %SLOT_NUM%, port %EMBRANCH_DAEMON_PORT%^)
) else (
    echo   Port:    %EMBRANCH_DAEMON_PORT%  ^(default, no version pin^)
)
echo   Binary:  %EMBRANCH_BIN%
echo   Logs:    %EMBRANCH_LOG_DIR%
echo.

REM --- Already running? ---
curl -s -o nul -w "%%{http_code}" --max-time 2 "%HEALTH_URL%" > "%TEMP%\embranch-health.txt" 2>nul
set /p HEALTH_CODE=<"%TEMP%\embranch-health.txt"
del "%TEMP%\embranch-health.txt" 2>nul
if "%HEALTH_CODE%"=="200" (
    echo [OK] Daemon already running on port %EMBRANCH_DAEMON_PORT%.
    goto end
)

REM --- Binary present? ---
if not exist "%EMBRANCH_BIN%" (
    echo [ERROR] Daemon binary not found:
    echo         %EMBRANCH_BIN%
    echo         Run Install-Daemon.ps1 first.
    set "_exit=1"
    goto end
)

REM --- Launch daemon with env var port (backward compatible with all binary versions) ---
echo Launching daemon on port %EMBRANCH_DAEMON_PORT% ...
if defined SLOT_NUM (
    powershell -NoProfile -NonInteractive -Command ^
      "$env:EMBRANCH_DAEMON_PORT = '%EMBRANCH_DAEMON_PORT%'; " ^
      "Start-Process -FilePath '%EMBRANCH_BIN%' -ArgumentList 'daemon','--slot','%SLOT_NUM%' -WindowStyle Hidden" ^
      >nul 2>&1
) else (
    powershell -NoProfile -NonInteractive -Command ^
      "$env:EMBRANCH_DAEMON_PORT = '%EMBRANCH_DAEMON_PORT%'; " ^
      "Start-Process -FilePath '%EMBRANCH_BIN%' -ArgumentList 'daemon' -WindowStyle Hidden" ^
      >nul 2>&1
)
if errorlevel 1 (
    echo [ERROR] Failed to spawn daemon process.
    set "_exit=1"
    goto end
)

REM --- Poll /health up to 15s ---
set /a _tries=0
:wait_start
timeout /t 1 /nobreak >nul
set /a _tries=_tries+1
curl -s -o nul -w "%%{http_code}" --max-time 2 "%HEALTH_URL%" > "%TEMP%\embranch-health.txt" 2>nul
set /p HEALTH_CODE=<"%TEMP%\embranch-health.txt"
del "%TEMP%\embranch-health.txt" 2>nul
if "%HEALTH_CODE%"=="200" (
    echo [OK] Daemon is up on port %EMBRANCH_DAEMON_PORT%.
    goto start_proxy
)
if %_tries% geq 15 (
    echo [ERROR] Daemon did not become healthy within 15 seconds.
    echo         Check logs: %EMBRANCH_LOG_DIR%
    set "_exit=1"
    goto end
)
goto wait_start

:start_proxy
REM --- Ensure proxy is running on 9473 (needed for .mcp.json URL routing) ---
curl -s -o nul -w "%%%%{http_code}" --max-time 2 "http://127.0.0.1:9473/health" > "%TEMP%\embranch-proxy.txt" 2>nul
set /p PROXY_CODE=<"%TEMP%\embranch-proxy.txt"
del "%TEMP%\embranch-proxy.txt" 2>nul
if "%PROXY_CODE%"=="200" goto end

echo Starting proxy on port 9473 ...
powershell -NoProfile -NonInteractive -Command ^
  "Start-Process -FilePath '%EMBRANCH_BIN%' -ArgumentList 'proxy' -WindowStyle Hidden" ^
  >nul 2>&1
timeout /t 3 /nobreak >nul
curl -s -o nul -w "%%%%{http_code}" --max-time 2 "http://127.0.0.1:9473/health" > "%TEMP%\embranch-proxy.txt" 2>nul
set /p PROXY_CODE=<"%TEMP%\embranch-proxy.txt"
del "%TEMP%\embranch-proxy.txt" 2>nul
if "%PROXY_CODE%"=="200" (
    echo [OK] Proxy is up on port 9473.
) else (
    echo [WARN] Proxy may not be running on port 9473.
)

:end
echo.
if %_exit% neq 0 (
    echo Press any key to close this window.
    pause >nul
) else (
    timeout /t 3 /nobreak >nul
)
endlocal & exit /b %_exit%