@echo off
setlocal EnableDelayedExpansion
title Start All Embranch Daemons

REM Generated by Install-Harness.ps1 v2.18.2
REM Emergency multi-version control: starts proxy + all registered daemon versions.

set "EMBRANCH_BIN_FALLBACK=%LOCALAPPDATA%\Embranch\daemon\current\embranch-daemon.exe"
set "SLOTS_JSON=%LOCALAPPDATA%\Embranch\slots.json"

REM --- EMBR-350: Resolve binary from default slot (latest version) ---
set "EMBRANCH_BIN=%EMBRANCH_BIN_FALLBACK%"
if exist "%SLOTS_JSON%" (
    for /f "tokens=*" %%B in ('powershell -NoProfile -NonInteractive -Command "$reg = Get-Content '%SLOTS_JSON%' -Raw | ConvertFrom-Json; $dk = [string]$reg.default_slot; if ($reg.slots.PSObject.Properties[$dk] -and $reg.slots.$dk.binary_path) { $reg.slots.$dk.binary_path }" 2^>nul') do set "EMBRANCH_BIN=%%B"
)

echo.
echo ============================================================
echo   Embranch -- Start All Daemons
echo ============================================================
echo   Binary: %EMBRANCH_BIN%
echo.

if not exist "%EMBRANCH_BIN%" (
    echo [ERROR] Daemon binary not found: %EMBRANCH_BIN%
    echo         Run Install-Daemon.ps1 first.
    goto end
)

if not exist "%SLOTS_JSON%" (
    echo [INFO] No slots.json found -- starting single daemon on default port.
    powershell -NoProfile -NonInteractive -Command "Start-Process -FilePath '%EMBRANCH_BIN%' -ArgumentList 'daemon' -WindowStyle Hidden"
    timeout /t 3 /nobreak >nul
    goto end
)

REM --- Kill existing manager first (prevents orphan respawning) ---
set "MANAGER_PID_FILE=%LOCALAPPDATA%\Embranch\run\manager.pid"
if exist "%MANAGER_PID_FILE%" (
    set /p MANAGER_PID=<"%MANAGER_PID_FILE%"
    echo Stopping existing manager PID !MANAGER_PID! ...
    taskkill /PID !MANAGER_PID! /F /T >nul 2>&1
    del "%MANAGER_PID_FILE%" >nul 2>&1
    timeout /t 2 /nobreak >nul
)

REM --- Stop any remaining process on port 9473 (proxy port) ---
echo Checking port 9473 ...
curl -s -o nul -w "%%{http_code}" --max-time 2 "http://127.0.0.1:9473/health" > "%TEMP%\embranch-health.txt" 2>nul
set /p PRE_HEALTH=<"%TEMP%\embranch-health.txt"
del "%TEMP%\embranch-health.txt" 2>nul
if "%PRE_HEALTH%"=="200" (
    echo [INFO] Something running on port 9473 -- stopping it first ...
    curl -s -X POST --max-time 3 "http://127.0.0.1:9473/admin/stop" >nul 2>&1
    timeout /t 2 /nobreak >nul
    for /f "tokens=5" %%P in ('netstat -ano 2^>nul ^| findstr ":9473 " ^| findstr LISTENING') do (
        taskkill /PID %%P /F /T >nul 2>&1
    )
    timeout /t 1 /nobreak >nul
)

REM --- Start manager (spawns proxy + all registered daemons under Job Object) ---
echo Starting manager (proxy + all slots) ...
powershell -NoProfile -NonInteractive -Command "Start-Process -FilePath '%EMBRANCH_BIN%' -ArgumentList 'manager' -WindowStyle Hidden"

echo.
echo [OK] Manager launched. Waiting 5s for health ...
timeout /t 5 /nobreak >nul

REM --- Quick health check ---
curl -s --max-time 2 "http://127.0.0.1:9473/api/v1/versions" > "%TEMP%\embranch-versions.json" 2>nul
for %%A in ("%TEMP%\embranch-versions.json") do if %%~zA gtr 0 (
    echo.
    echo [VERSIONS]
    type "%TEMP%\embranch-versions.json"
    echo.
)
del "%TEMP%\embranch-versions.json" 2>nul

:end
echo.
echo Press any key to close this window.
pause >nul
endlocal & exit /b 0