@echo off
setlocal EnableDelayedExpansion
title Stop Embranch Daemon (TEST)

REM Generated by Install-Harness.ps1 v2.18.2
REM Project: TEST  (D:\Extracted\260521_GitTest\ProjectA)

set "EMBRANCH_DEFAULT_PORT=9473"
set "EMBRANCH_BIN_NAME=embranch-daemon.exe"
set "EMBRANCH_LOG_DIR=%LOCALAPPDATA%\Embranch\logs"
set "EMBRANCH_SHUTDOWN_TOKEN_FILE=%LOCALAPPDATA%\Embranch\shutdown.token"
set "SLOTS_JSON=%LOCALAPPDATA%\Embranch\slots.json"
set "MCP_JSON=D:\Extracted\260521_GitTest\ProjectA\.mcp.json"
set "_exit=0"

REM --- EMBR-350: Detect version from .mcp.json and resolve port ---
set "EMBRANCH_DAEMON_PORT=%EMBRANCH_DEFAULT_PORT%"
set "PINNED_VERSION="

if not exist "%MCP_JSON%" goto skip_version_detect
for /f "tokens=*" %%L in ('powershell -NoProfile -NonInteractive -Command "$mcp = Get-Content $env:MCP_JSON -Raw | ConvertFrom-Json; $url = $mcp.mcpServers.psdd.url; if ($url -match '/embranch/v([^/]+)/') { $Matches[1] }" 2^>nul') do set "PINNED_VERSION=%%L"
:skip_version_detect

if not exist "%SLOTS_JSON%" goto skip_slot_resolve
if not defined PINNED_VERSION goto resolve_default_slot

REM --- Pinned version: find matching slot ---
for /f "tokens=1,2" %%A in ('powershell -NoProfile -NonInteractive -Command "$reg = Get-Content $env:SLOTS_JSON -Raw | ConvertFrom-Json; foreach ($p in $reg.slots.PSObject.Properties) { if ($p.Value.version -eq $env:PINNED_VERSION) { Write-Output ($p.Name + ' ' + $p.Value.internal_port); break } }" 2^>nul') do set "EMBRANCH_DAEMON_PORT=%%B"
goto skip_slot_resolve

:resolve_default_slot
REM --- No pin: use default slot from slots.json ---
for /f "tokens=1,2" %%A in ('powershell -NoProfile -NonInteractive -Command "$reg = Get-Content $env:SLOTS_JSON -Raw | ConvertFrom-Json; $dk = [string]$reg.default_slot; if ($reg.slots.PSObject.Properties[$dk]) { Write-Output ($dk + ' ' + $reg.slots.$dk.internal_port) }" 2^>nul') do set "EMBRANCH_DAEMON_PORT=%%B"

:skip_slot_resolve

set "ADMIN_URL=http://127.0.0.1:%EMBRANCH_DAEMON_PORT%/admin/stop"
set "HEALTH_URL=http://127.0.0.1:%EMBRANCH_DAEMON_PORT%/health"

echo.
echo Embranch Daemon -- Stop
echo   Project: TEST
if defined PINNED_VERSION (
    echo   Pinned:  v%PINNED_VERSION%  ^(port %EMBRANCH_DAEMON_PORT%^)
) else (
    echo   Port:    %EMBRANCH_DAEMON_PORT%
)
echo   Logs:    %EMBRANCH_LOG_DIR%
echo.

REM --- Is the daemon up? ---
curl -s -o nul -w "%%{http_code}" --max-time 2 "%HEALTH_URL%" > "%TEMP%\embranch-health.txt" 2>nul
set /p HEALTH_CODE=<"%TEMP%\embranch-health.txt"
del "%TEMP%\embranch-health.txt" 2>nul
if not "%HEALTH_CODE%"=="200" (
    echo [OK] Daemon already stopped ^(no response on port %EMBRANCH_DAEMON_PORT%^).
    goto end
)

REM --- Read shutdown token (required for /admin/stop auth) ---
REM The daemon's /admin/stop endpoint requires Authorization: Bearer <token>.
REM The token is written to %LOCALAPPDATA%\Embranch\shutdown.token by
REM Install-Daemon.ps1. Without it, POST /admin/stop is rejected (401/403)
REM and we silently fall through to the force-kill path -- which works but
REM is noisier and may take the full 10-second timeout.
set "EMBRANCH_TOKEN="
if exist "%EMBRANCH_SHUTDOWN_TOKEN_FILE%" (
    set /p EMBRANCH_TOKEN=<"%EMBRANCH_SHUTDOWN_TOKEN_FILE%"
)

REM --- Graceful shutdown request ---
if defined EMBRANCH_TOKEN (
    echo Requesting graceful shutdown ^(authorized^) ...
    curl -s -X POST --max-time 5 -H "Authorization: Bearer %EMBRANCH_TOKEN%" "%ADMIN_URL%" >nul 2>&1
) else (
    echo [WARN] No shutdown.token found at %EMBRANCH_SHUTDOWN_TOKEN_FILE%
    echo        Skipping graceful shutdown, going straight to force-kill.
    goto force_kill
)

REM --- Poll /health up to 10s ---
set /a _tries=0
:wait_stop
timeout /t 1 /nobreak >nul
set /a _tries=_tries+1
curl -s -o nul -w "%%{http_code}" --max-time 2 "%HEALTH_URL%" > "%TEMP%\embranch-health.txt" 2>nul
set /p HEALTH_CODE=<"%TEMP%\embranch-health.txt"
del "%TEMP%\embranch-health.txt" 2>nul
if not "%HEALTH_CODE%"=="200" (
    echo [OK] Embranch daemon stopped.
    goto end
)
if %_tries% geq 10 goto force_kill
goto wait_stop

:force_kill
REM Use /T (tree kill) so PyInstaller bootstrap + its extracted child
REM process are both terminated. Without /T only the parent exits and
REM the real Python runtime keeps listening on the port.
echo [WARN] Force killing %EMBRANCH_BIN_NAME% (tree kill) ...
taskkill /IM %EMBRANCH_BIN_NAME% /F /T >nul 2>&1

REM Belt-and-braces: also kill by PID from a PowerShell fallback in case
REM the image name does not match (e.g. a versioned build next to an
REM unversioned one) or Windows reports the process under a different name.
for /f "tokens=5" %%P in ('netstat -ano ^| findstr ":%EMBRANCH_DAEMON_PORT% " ^| findstr LISTENING') do (
    taskkill /PID %%P /F /T >nul 2>&1
)

timeout /t 1 /nobreak >nul
curl -s -o nul -w "%%{http_code}" --max-time 2 "%HEALTH_URL%" > "%TEMP%\embranch-health.txt" 2>nul
set /p HEALTH_CODE=<"%TEMP%\embranch-health.txt"
del "%TEMP%\embranch-health.txt" 2>nul
if "%HEALTH_CODE%"=="200" (
    echo [ERROR] Daemon still responding on port %EMBRANCH_DAEMON_PORT% after force-kill.
    set "_exit=1"
    goto end
)
echo [OK] Embranch daemon stopped (force-killed).

:end
echo.
echo Press any key to close this window.
pause >nul
endlocal & exit /b %_exit%