@echo off
setlocal EnableDelayedExpansion
title Stop All Embranch Daemons

REM Generated by Install-Harness.ps1 v2.18.2
REM Graceful multi-version shutdown: HTTP first, force-kill fallback.

set "EMBRANCH_BIN_NAME=embranch-daemon.exe"
set "EMBRANCH_SHUTDOWN_TOKEN_FILE=%LOCALAPPDATA%\Embranch\shutdown.token"
set "SLOTS_JSON=%LOCALAPPDATA%\Embranch\slots.json"
set "MANAGER_PORT_FILE=%LOCALAPPDATA%\Embranch\run\manager.port"
set "MANAGER_PID_FILE=%LOCALAPPDATA%\Embranch\run\manager.pid"

echo.
echo ============================================================
echo   Embranch -- Stop All Daemons
echo ============================================================
echo.

REM --- Read shutdown token ---
set "EMBRANCH_TOKEN="
if exist "%EMBRANCH_SHUTDOWN_TOKEN_FILE%" (
    set /p EMBRANCH_TOKEN=<"%EMBRANCH_SHUTDOWN_TOKEN_FILE%"
)

REM --- Step 1: Stop manager via /admin/stop (cascades to all children) ---
set "MANAGER_PORT=9472"
if exist "%MANAGER_PORT_FILE%" (
    set /p MANAGER_PORT=<"%MANAGER_PORT_FILE%"
)
echo Sending cascade shutdown to manager on port !MANAGER_PORT! ...
curl -s -X POST --max-time 3 "http://127.0.0.1:!MANAGER_PORT!/admin/stop" >nul 2>&1
if !errorlevel! equ 0 (
    echo   Manager acknowledged shutdown -- waiting for cascade ...
    timeout /t 5 /nobreak >nul
    goto verify
)
echo   Manager unreachable -- falling back to per-process shutdown.
echo.

REM --- Step 2 (fallback): Stop each slot's daemon via /admin/stop ---
if not exist "%SLOTS_JSON%" goto skip_slots

echo Stopping daemons from slots.json ...
powershell -NoProfile -NonInteractive -Command ^
  "$reg = Get-Content '%SLOTS_JSON%' -Raw | ConvertFrom-Json; " ^
  "foreach ($p in $reg.slots.PSObject.Properties) { " ^
  "  $port = $p.Value.internal_port; $ver = $p.Value.version; " ^
  "  Write-Host \"  Stopping slot $($p.Name) (v$ver) on port $port ...\"; " ^
  "  try { Invoke-RestMethod -Uri \"http://127.0.0.1:$port/admin/stop\" -Method Post -TimeoutSec 3 -ErrorAction SilentlyContinue | Out-Null } catch {} " ^
  "}"
echo.

:skip_slots

REM --- Step 3 (fallback): Stop proxy ---
echo Stopping proxy on port 9473 ...
if defined EMBRANCH_TOKEN (
    curl -s -X POST --max-time 3 -H "Authorization: Bearer %EMBRANCH_TOKEN%" "http://127.0.0.1:9473/admin/stop" >nul 2>&1
) else (
    curl -s -X POST --max-time 3 "http://127.0.0.1:9473/admin/stop" >nul 2>&1
)

timeout /t 3 /nobreak >nul

REM --- Step 4: Kill manager process (best effort) ---
if exist "%MANAGER_PID_FILE%" (
    set /p MANAGER_PID=<"%MANAGER_PID_FILE%"
    echo Killing manager process PID !MANAGER_PID! ...
    taskkill /PID !MANAGER_PID! /F /T >nul 2>&1
    del "%MANAGER_PID_FILE%" >nul 2>&1
)

REM --- Step 5: Force kill any remaining processes ---
echo Force-killing any remaining embranch processes ...
taskkill /IM %EMBRANCH_BIN_NAME% /F /T >nul 2>&1

timeout /t 1 /nobreak >nul

:verify
REM --- Step 6: Verify all processes are gone ---
set "_remaining=0"
for /f %%N in ('tasklist /FI "IMAGENAME eq %EMBRANCH_BIN_NAME%" /NH 2^>nul ^| find /c "%EMBRANCH_BIN_NAME%"') do set "_remaining=%%N"
if %_remaining% gtr 0 (
    echo.
    echo [WARN] %_remaining% embranch process^(es^) still running.
    echo        Orphan daemons will self-terminate within ~90 seconds.
    echo        To stop immediately, run this bat as Administrator.
) else (
    echo.
    echo [OK] All Embranch daemons stopped.
)

echo.
echo Press any key to close this window.
pause >nul
endlocal & exit /b 0